### ISSUE TITLE
grad_process

### ISSUE THREAD

**Issue by GuideWsp** [DandilionLau/Selfie-Friendly-Abstraction#1]
can you provide the grad_process which will be used in test.m.

**Comment by GuideWsp** [comment]
i load a grad_procss.p from https://github.com/jimmy-ren/vcnn_double-bladed/tree/master/applications/deep_edge_aware_filters/utility. but when running, it tells "p file notvalid", so, can you provide a valid p file, thanks. My platform is win7, matlab2016a.

**Comment by DandilionLau** [comment]
Hi. I made a bit update and now grad_process.p is in the /utils folder. You may pull this repo again and now test_6chs_reshape.m should be ready for inference.

**Comment by GuideWsp** [comment]
thanks, now i can run it.
